name: Remove old artifacts

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
    # Every day at 1am
    # - cron: '0 1 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '90 seconds' # '<number> <unit>', e.g. 1 month, 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
